# A try block without an except or finally block is pretty useless, so an except or finally is indeed required.

# You can have as many except blocks as you want, and you can do whatever you want in them.

# However, you can only have one finally block, and it's not required if you have at least one except before it.

# The finally block, if present, must appear after all except blocks in a try/except statement.

# In many other programming languages, you "throw" an exception or error. In Python, however, you "raise" them

"""

Python is an interpreted language, which means that all exceptions other than syntax errors occur at run-time, while the program is being executed.

For example, if you try executing [0, 1, 2][3] in Python, the code will indeed be executed, and the resulting IndexError will be raised at run-time.

If syntax errors are present, however, the interpreter will catch them before executing the program and inform you that it can't understand the code that you've written.

For example, if you try executing []] in Python, the code won't be executed, and a SyntaxError will instead be raised.

"""

"""

# Write your code here.

# You'll have to use the following strings:

# 1) "Enter the numerator: "
# 2) "Enter the denominator: "
# 3) "The numerator is not a number."
# 4) "The denominator is not a number."
# 5) "You cannot divide by 0."
# 6) "This division cannot be performed."
# 7) "The result of this division is _."
# 8) "Goodbye!"

result = 0
numer = input("Enter the numerator: ")
deno = input("Enter the denominator: ")
try:
    numer = float(numer)
except Exception as e:
    print("The numerator is not a number.")

try:
    deno = float(deno)
except Exception as e:
    print("The denominator is not a number.")


try:
    result = int(numer)/ int(deno)
    print(f"The result of this division is {result}.")

except ZeroDivisionError:
    print("You cannot divide by 0.")
    print("This division cannot be performed.")
except TypeError:
    print("This division cannot be performed.")

except ValueError:
    print("This division cannot be performed.")

finally:
    print("Goodbye!")
"""